# Generated by Django 2.2.4 on 2019-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191120_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='key',
            field=models.CharField(default='3bd9ef87a8de4633a588904d24a64670905a3375687ae52e3daeba82dd702269', max_length=256),
        ),
    ]
