# Generated by Django 2.2.4 on 2019-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='key',
            field=models.CharField(default='RV3QPhJzUZfi7NXHaDfKVSnPkjV2D0aQ1Ek0zlxjyr2LS21U2Q87yZr3vLN5vKBE3bw6chnX0auHVehmtpfuBH6vfjylZVbxXIODk9vGHf59Q1xxwk4BtLPncrffRFF2', max_length=256),
        ),
    ]
